# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('sponserId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('plan', models.IntegerField()),
                ('joiningDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNo', models.CharField(max_length=200)),
                ('IFSCCode', models.CharField(max_length=200)),
                ('holderName', models.CharField(max_length=100)),
                ('bankName', models.CharField(max_length=200)),
                ('accountType', models.BooleanField()),
                ('panNo', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User', to_field=b'username')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User', to_field=b'username')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.CharField(max_length=10)),
                ('lChild', models.CharField(max_length=10)),
                ('rChild', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('sponserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User', to_field=b'username')),
            ],
        ),
    ]
