# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='lChild',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='rChild',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='sponserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
