# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170613_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='sponserId',
            field=models.CharField(max_length=10),
        ),
    ]
