# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170613_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='lChild',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='rChild',
        ),
    ]
