# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170613_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='joiningDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.IntegerField(blank=True),
        ),
    ]
