# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170613_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='aadhaarCard',
            field=models.BinaryField(default=b'Blank'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='aadhaarNo',
            field=models.CharField(default=b'Blank', max_length=200),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='branchName',
            field=models.CharField(default=b'Blank', max_length=200),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='panCard',
            field=models.BinaryField(default=b'Blank'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='firstName',
            field=models.CharField(default=b'Blank', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastName',
            field=models.CharField(default=b'Blank', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='panNo',
            field=models.CharField(default=b'Blank', max_length=200),
        ),
    ]
