# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170616_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='photo',
            field=models.BinaryField(default=b'Blank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
