# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170716_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.CharField(default=123, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
