# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170720_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additionalImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='primaryImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondaryImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='specialproduct',
            name='additionalImage',
        ),
        migrations.RemoveField(
            model_name='specialproduct',
            name='primaryImage',
        ),
        migrations.RemoveField(
            model_name='specialproduct',
            name='secondaryImage',
        ),
        migrations.RemoveField(
            model_name='specialproduct',
            name='slug',
        ),
    ]
