# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170720_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additionalImage',
            field=models.ImageField(default=b'products/None/placeholderImage.png', upload_to=b'products/images3/'),
        ),
        migrations.AddField(
            model_name='product',
            name='primaryImage',
            field=models.ImageField(default=b'products/None/placeholderImage.png', upload_to=b'products/images1/'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondaryImage',
            field=models.ImageField(default=b'products/None/placeholderImage.png', upload_to=b'products/images2/'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='additionalImage',
            field=models.ImageField(default=b'products/None/placeholderImage.png', upload_to=b'products/images3/'),
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='primaryImage',
            field=models.ImageField(default=b'products/None/placeholderImage.png', upload_to=b'products/images1/'),
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='secondaryImage',
            field=models.ImageField(default=b'products/None/placeholderImage.png', upload_to=b'products/images2/'),
        ),
        migrations.AddField(
            model_name='specialproduct',
            name='slug',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
