# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
