# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170727_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additionalImage',
            field=models.ImageField(default=b'product/None/placeholderImage.png', upload_to=b'product/images3/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primaryImage',
            field=models.ImageField(default=b'product/None/placeholderImage.png', upload_to=b'product/images1/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondaryImage',
            field=models.ImageField(default=b'product/None/placeholderImage.png', upload_to=b'product/images2/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=b'product/images/'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='additionalImage',
            field=models.ImageField(default=b'product/None/placeholderImage.png', upload_to=b'product/images3/'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='primaryImage',
            field=models.ImageField(default=b'product/None/placeholderImage.png', upload_to=b'product/images1/'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='secondaryImage',
            field=models.ImageField(default=b'product/None/placeholderImage.png', upload_to=b'product/images2/'),
        ),
    ]
