# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170727_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sponserId',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='sponserId',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
