# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_specialproduct_cashbackdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelation',
            name='childUsername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrelation',
            name='parentUsername',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
