# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20170820_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
