# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_useraccount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='joiningDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
