# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_useraccount_joiningdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelation',
            name='cashRewardPrentWillRecieve',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
