# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_userrelation_cashrewardprentwillrecieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrefferal',
            name='monthlyCashbackAmount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
