# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_userrefferal_monthlycashbackamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='productId',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
