# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_useraccount_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='photo',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.TextField(default=b'Blank'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default=b'Blank', max_length=254),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='firstName',
            field=models.CharField(default=b'Blank', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='lastName',
            field=models.CharField(default=b'Blank', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phoneNo',
            field=phonenumber_field.modelfields.PhoneNumberField(default=b'Blank', max_length=128),
        ),
    ]
