# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20170905_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalProductsBoughtList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('firstName', models.CharField(default=b'Blank', max_length=100)),
                ('lastName', models.CharField(default=b'Blank', max_length=100)),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(default=b'Blank', max_length=128)),
                ('address', models.TextField(default=b'Blank')),
                ('email', models.EmailField(default=b'Blank', max_length=254)),
                ('product', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=10000.0, max_digits=100)),
                ('boughtDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
