# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_normalproductsboughtlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='city',
            field=models.CharField(default=b'delhi', max_length=20),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='pinCode',
            field=models.IntegerField(default=110001, max_length=20),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='state',
            field=models.CharField(default=b'delhi', max_length=20),
        ),
    ]
