# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20170914_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pinCode',
            field=models.IntegerField(default=110001),
        ),
    ]
