# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20170914_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joiningDate',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
    ]
