# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20170914_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalproductsboughtlist',
            name='boughtDate',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='updated',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='joiningDate',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
    ]
