# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20170914_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='normalproductsboughtlist',
            name='product',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
