# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_useraccountactual_userrefferalactual_userrelationactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrefferal',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userrefferalactual',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
